"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {usePathname,useRouter} from "next/navigation";
import {LayoutGroup,motion,useReducedMotion} from "motion/react";
import ClubBadge from "./ClubBadge";
const groups=[
 {label:'Archive',items:[['/players','Players'],['/matches','Matches'],['/head-to-head','Head-to-Head'],['/seasons','Seasons'],['/transfers','Transfers'],['/competitions','Competitions']]},
 {label:'Club',items:[['/managers','Managers'],['/records','Honours & Records'],['/greatest-50','Greatest 50'],['/timeline','Timeline'],['/europe','European History']]},
 {label:'Interactive',items:[['/interactive','Games Hub'],['/team-picker','Ultimate XI'],['/on-this-day','On This Day'],['/polls','Supporter Polls'],['/polls/cult-heroes','Cult Heroes Poll'],['/interactive/pardle','Pardle'],['/interactive/career-path','Career Path'],['/interactive/higher-lower','Higher or Lower'],['/interactive/starting-xi','Starting XI']]}
];
export default function SiteHeader(){const path=usePathname();const router=useRouter();const reduced=useReducedMotion();const [q,setQ]=useState('');const [open,setOpen]=useState<string|null>(null);const [mobile,setMobile]=useState(false);
useEffect(()=>{setOpen(null);setMobile(false)},[path]);
useEffect(()=>{if(!mobile)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMobile(false);setOpen(null)}};window.addEventListener('keydown',esc);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',esc)}},[mobile]);
function closeMobile(){setMobile(false);setOpen(null)}function submit(e:FormEvent){e.preventDefault();if(q.trim()){router.push(`/search/?q=${encodeURIComponent(q.trim())}`);closeMobile()}}
return <header className={`siteHeader ${mobile?'mobileOpen':''}`}><Link className="brand" href="/" aria-label="Pars Database home" onClick={closeMobile}><span className="navCrest"><ClubBadge name="Dunfermline Athletic" size="sm"/></span><span className="brandWord">PARS<span>DATABASE</span></span></Link><motion.button className="mobileMenu" type="button" aria-label={mobile?'Close navigation':'Open navigation'} aria-expanded={mobile} aria-controls="primary-navigation" whileTap={reduced?undefined:{scale:.92}} onClick={()=>setMobile(v=>!v)}><i/><i/><i/></motion.button><LayoutGroup id="primary-navigation-motion"><nav id="primary-navigation" className="siteNav groupedNav" aria-label="Primary navigation">{groups.map(g=>{const active=g.items.some(([href])=>path?.startsWith(href));return <div className={`navGroup ${active?'active':''} ${open===g.label?'open':''}`} key={g.label}><motion.button type="button" whileTap={reduced?undefined:{scale:.97}} onClick={()=>setOpen(open===g.label?null:g.label)} aria-expanded={open===g.label}>{g.label}<span>⌄</span>{active&&<motion.i className="navMotionIndicator" layoutId="nav-active-indicator" transition={reduced?{duration:0}:{type:'spring',stiffness:520,damping:38,mass:.55}}/>}</motion.button><div className="navDropdown">{g.items.map(([href,label],i)=><Link onClick={closeMobile} className={`${path?.startsWith(href)?'active':''} ${g.label==='Interactive'&&i===0?'hubLink':''}`} href={href} key={href}>{label}<b>→</b></Link>)}</div></div>})}</nav></LayoutGroup><form className="globalSearch" onSubmit={submit} role="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the archive" aria-label="Search the archive"/><button aria-label="Search">Search</button></form></header>}
