"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {usePathname,useRouter} from "next/navigation";
import ClubBadge from "./ClubBadge";
const groups=[
 {label:'Archive',items:[['/players','Players'],['/matches','Matches'],['/seasons','Seasons'],['/competitions','Competitions']]},
 {label:'Club',items:[['/managers','Managers'],['/records','Honours & Records'],['/greatest-50','Greatest 50'],['/timeline','Timeline'],['/europe','European History']]},
 {label:'Interactive',items:[['/interactive','Games Hub'],['/team-picker','Ultimate XI'],['/on-this-day','On This Day'],['/polls','Supporter Polls'],['/interactive/pardle','Pardle'],['/interactive/career-path','Career Path'],['/interactive/higher-lower','Higher or Lower'],['/interactive/starting-xi','Starting XI']]}
];
export default function SiteHeader(){const path=usePathname();const router=useRouter();const [q,setQ]=useState('');const [open,setOpen]=useState<string|null>(null);const [mobile,setMobile]=useState(false);useEffect(()=>{setOpen(null);setMobile(false)},[path]);useEffect(()=>{if(!mobile)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[mobile]);function submit(e:FormEvent){e.preventDefault();if(q.trim()){router.push(`/search/?q=${encodeURIComponent(q.trim())}`);setMobile(false)}}return <header className={`siteHeader ${mobile?'mobileOpen':''}`} style={mobile?{maxHeight:'100dvh',overflowY:'auto',overscrollBehavior:'contain',WebkitOverflowScrolling:'touch',paddingBottom:'max(1.5rem, env(safe-area-inset-bottom))'}:undefined}><Link className="brand" href="/" aria-label="Pars Database home"><span className="navCrest"><ClubBadge name="Dunfermline Athletic" size="sm"/></span><span className="brandWord">PARS<span>DATABASE</span></span></Link><button className="mobileMenu" type="button" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}><i/><i/><i/></button><nav className="siteNav groupedNav" aria-label="Primary navigation">{groups.map(g=>{const active=g.items.some(([href])=>path?.startsWith(href));return <div className={`navGroup ${active?'active':''} ${open===g.label?'open':''}`} key={g.label}><button type="button" onClick={()=>setOpen(open===g.label?null:g.label)} aria-expanded={open===g.label}>{g.label}<span>⌄</span></button><div className="navDropdown">{g.items.map(([href,label],i)=><Link className={`${path?.startsWith(href)?'active':''} ${g.label==='Interactive'&&i===0?'hubLink':''}`} href={href} key={href}>{label}<b>→</b></Link>)}</div></div>})}</nav><form className="globalSearch" onSubmit={submit} role="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the archive" aria-label="Search the archive"/><button aria-label="Search">Search</button></form></header>}
