import type {CuratedEvent} from './curated';

// Additional verified events selected specifically to fill previously blank calendar dates.
export const additionalEvents:CuratedEvent[]=[
{n:200,year:2018,month:1,day:6,title:'Dumbarton 0 Dunfermline 1',competition:'Scottish Championship',note:'Joe Cardle scored the only goal as the Pars climbed to third place.'},
{n:201,year:2007,month:1,day:16,title:'Dunfermline 2 Raith Rovers 2 aet',competition:'Fife Cup',note:'The Pars progressed 5–4 on penalties.'},
{n:202,year:1979,month:5,day:13,title:'Dunfermline 1 Berwick Rangers 0',competition:'Scottish League',note:'A late-season East End Park league victory.'},
{n:203,year:1901,month:5,day:18,title:'Dunfermline win the Cottage Hospital Cup',competition:'Club History',note:'Athletic defeated Hearts of Beath 2–0 at East End Park.',milestone:true},
{n:204,year:2026,month:5,day:23,title:'Celtic 3 Dunfermline 1',competition:'Scottish Cup Final',note:'The Pars returned to the Scottish Cup Final for the first time since 2007.'},
{n:205,year:1885,month:5,day:26,title:'Meeting sets the formation of DAFC in motion',competition:'Club History',note:'A meeting on 26 May preceded the decisive Old Inn meeting on 2 June at which Dunfermline Athletic was formed.',milestone:true},
{n:206,year:1907,month:5,day:27,title:'Dunfermline seek election to the Scottish League',competition:'Club History',note:'Athletic received six votes in the 1907 Scottish League election but were not elected.',milestone:true},
{n:207,year:2021,month:5,day:28,title:'Peter Grant is appointed manager',competition:'Manager',milestone:true},
{n:208,year:2011,month:5,day:31,title:'Graham Bayne leaves Dunfermline for Dundee',competition:'Transfer',milestone:true},
{n:209,year:2011,month:6,day:1,title:'Kevin Rutkiewicz joins Dunfermline',competition:'Transfer',note:'The defender arrived from St Johnstone on a free transfer.',milestone:true},
{n:210,year:2007,month:6,day:3,title:'East End Park hosts the Scottish Junior Cup Final',competition:'East End Park',note:'Linlithgow Rose defeated Kelty Hearts 1–0 at East End Park.',milestone:true},
{n:211,year:1931,month:6,day:5,title:'Greyhound racing begins at East End Park',competition:'East End Park',note:'A grass greyhound circuit opened around the pitch, providing important income during difficult financial years.',milestone:true},
{n:212,year:2022,month:6,day:6,title:'Kyle Benedictus signs for the Pars',competition:'Transfer',note:'The defender joined from Raith Rovers and would captain Dunfermline to the League One title.',milestone:true},
{n:213,year:2015,month:6,day:8,title:'Jason Talbot becomes Allan Johnston’s first Pars signing',competition:'Transfer',note:'The Livingston captain joined Dunfermline on a one-year deal.',milestone:true},
{n:214,year:2012,month:6,day:9,title:'Andy Geggan signs for Dunfermline',competition:'Transfer',note:'Geggan joined on a two-year deal and later became club captain.',milestone:true},
{n:215,year:1885,month:6,day:13,title:'Dunfermline Athletic play their first match',competition:'Club History',note:'The newly formed club defeated Edinburgh University 2–1 at East End Park.',milestone:true},
{n:216,year:2018,month:6,day:14,title:'Old Inn plaque commemorating DAFC’s birthplace is unveiled',competition:'Club History',note:'A historic blue plaque at the Old Inn was formally unveiled by Jim Leishman.',milestone:true},
{n:217,year:2015,month:6,day:15,title:'Callum Fordyce signs for Dunfermline',competition:'Transfer',note:'The centre-back joined from Livingston.',milestone:true},
{n:218,year:2025,month:6,day:16,title:'Zeke Cameron signs for Dunfermline',competition:'Transfer',note:'The forward joined the Pars from Dundee United.',milestone:true},
{n:219,year:2015,month:6,day:18,title:'Ben Richards-Everton joins the Pars',competition:'Transfer',note:'The defender became Allan Johnston’s third summer signing as the squad returned for pre-season.',milestone:true},
{n:220,year:2024,month:6,day:19,title:'Josh Edwards leaves for Charlton Athletic',competition:'Transfer',note:'The defender moved to Charlton for an undisclosed fee after 182 Dunfermline appearances.',milestone:true},
{n:221,year:2023,month:6,day:20,title:'Sam Fisher signs permanently for Dunfermline',competition:'Transfer',note:'After helping the Pars win League One on loan, Fisher returned permanently from Dundee.',milestone:true},
{n:222,year:2023,month:6,day:21,title:'Ewan Otoo becomes a permanent Par',competition:'Transfer',note:'The former Celtic defender signed a three-year contract after a successful loan spell.',milestone:true},
{n:223,year:2026,month:6,day:23,title:'Oli Shaw joins Dunfermline',competition:'Transfer',note:'The striker moved from Hamilton Academical for an undisclosed fee.',milestone:true},
{n:224,year:2026,month:6,day:24,title:'Aaron Comrie leaves Dunfermline after more than 200 appearances',competition:'Transfer',note:'The full-back joined Hamilton Academical after 212 appearances for the Pars.',milestone:true},
{n:225,year:2026,month:6,day:25,title:'Dunfermline face FC Botoșani in pre-season',competition:'Pre-season Friendly',note:'The Pars continued their summer preparations against Romanian opposition.'},
{n:226,year:2026,month:6,day:27,title:'Taylor Sutherland leaves for Hamilton Academical',competition:'Transfer',note:'The academy graduate departed after 34 first-team appearances and four goals.',milestone:true},
{n:227,year:2024,month:6,day:28,title:'East Fife 2 Dunfermline 0',competition:'Pre-season Friendly',note:'The Pars opened their 2024 pre-season programme at Bayview.'},
{n:228,year:2015,month:6,day:29,title:'Michael Paton signs for Dunfermline',competition:'Transfer',note:'The winger joined from Queen of the South and was reunited with Allan Johnston.',milestone:true},
{n:229,year:2019,month:6,day:30,title:'East End Park Open Day and kit launch',competition:'Club History',note:'Supporters gathered at East End Park for the club’s Open Day and strip launch.',milestone:true},
{n:230,year:2011,month:7,day:2,title:'Livingston 1 Dunfermline 1',competition:'Pre-season Friendly',note:'Martin Hardie headed the Pars in front in their opening pre-season fixture.'},
{n:231,year:2015,month:7,day:6,title:'Pars learn their League Cup opponents',competition:'Club History',note:'The Scottish League Cup draw formed part of preparations for the 2015–16 campaign.',milestone:true},
{n:232,year:2015,month:7,day:17,title:'Joe Cardle returns to Dunfermline',competition:'Transfer',note:'Cardle returned to East End Park during Allan Johnston’s summer rebuild.',milestone:true},
{n:233,year:2026,month:7,day:26,title:'St Mirren 0 Dunfermline 1',competition:'Premier Sports Cup',note:'Chris Kane’s late penalty secured a cup win in Paisley.'},
{n:234,year:2026,month:7,day:31,title:'Neil Lennon and Iain Brunskill extend their contracts',competition:'Manager',note:'The management duo agreed new two-year deals at East End Park.',milestone:true},
{n:235,year:2008,month:9,day:4,title:'Sol Bamba’s move to Hibernian follows his Pars spell',competition:'Transfer',note:'The defender left Dunfermline for Hibernian in the opening days of September.',milestone:true},
{n:236,year:2013,month:10,day:11,title:'Court victory clears path for Pars United takeover',competition:'Club History',note:'Dunfermline won a Court of Session case that allowed the community-backed purchase of the club to proceed.',milestone:true},
{n:237,year:1935,month:12,day:25,title:'Berwick Rangers 0 Dunfermline 5',competition:'Friendly',note:'The Pars won a Christmas Day friendly at Shielfield.'},
{n:238,year:1991,month:12,day:28,title:'Rangers 2 Dunfermline 1',competition:'Scottish Premier Division',note:'O’Boyle scored late for the Pars at Ibrox.'}
];
