export type CuratedEvent={n:number;year:number;month:number;day:number;title:string;competition:string;note?:string;milestone?:boolean};

export const curatedEvents:CuratedEvent[]=[
{n:124,year:1920,month:2,day:26,title:'Andy Wilson becomes the first Pars player capped by Scotland',competition:'International',note:'Wilson won his first full Scotland cap while a Dunfermline Athletic player.',milestone:true},
{n:123,year:1921,month:5,day:14,title:'Dunfermline return to the Scottish League',competition:'Club History',note:'The club was admitted to the newly created Second Division.',milestone:true},
{n:122,year:1922,month:3,day:13,title:'William Knight becomes Dunfermline’s first manager',competition:'Manager',milestone:true},
{n:121,year:1930,month:9,day:27,title:'Dunfermline record an 11–2 league victory',competition:'Club Record',note:'The win over Stenhousemuir remains the club’s record league victory.',milestone:true},
{n:120,year:1960,month:3,day:14,title:'Jock Stein is appointed manager',competition:'Manager',note:'Stein arrived at East End Park for his first managerial role and transformed the club’s fortunes.',milestone:true},
{n:119,year:1968,month:4,day:30,title:'Record East End Park attendance',competition:'Club Record',note:'27,816 watched Dunfermline face Celtic, the highest recorded attendance at East End Park.',milestone:true},
{n:118,year:1983,month:10,day:17,title:'Jim Leishman is appointed manager',competition:'Manager',note:'The appointment began the era that carried the Pars from the lower divisions back to the top flight.',milestone:true},
{n:117,year:1989,month:8,day:9,title:'István Kozma joins for a club-record fee',competition:'Transfer',note:'Dunfermline paid £540,000 for the Hungarian midfielder.',milestone:true},
{n:116,year:1993,month:6,day:10,title:'Bert Paton is appointed manager',competition:'Manager',milestone:true},
{n:115,year:1995,month:10,day:4,title:'Jackie McNamara joins Celtic for a club-record sale',competition:'Transfer',milestone:true},
{n:114,year:1996,month:1,day:8,title:'Remembering Norrie McCathie',competition:'Club History',note:'Club captain Norrie McCathie died suddenly aged 34. The North Stand at East End Park was later named in his memory.',milestone:true},
{n:113,year:1999,month:11,day:30,title:'Jimmy Calderwood is appointed manager',competition:'Manager',milestone:true},
{n:112,year:2008,month:1,day:3,title:'Jim McIntyre takes charge',competition:'Manager',milestone:true},
{n:111,year:2022,month:5,day:24,title:'James McPake is appointed manager',competition:'Manager',milestone:true},
{n:110,year:1885,month:6,day:2,title:'Dunfermline Athletic Football Club is formed',competition:'Club History',note:'Sixty members attended the inaugural meeting at the Old Inn in Kirkgate, creating Dunfermline Athletic Football Club.',milestone:true},
{n:109,year:1959,month:10,day:26,title:'East End Park floodlights are inaugurated',competition:'East End Park',note:'The new floodlighting system was switched on for a special match against Sheffield United.',milestone:true},
{n:108,year:1989,month:6,day:11,title:'Remembering Gary Riddell',competition:'Club History',note:'The 22-year-old Dunfermline centre-half died while running to raise money for victims of the Hillsborough disaster.',milestone:true},
{n:107,year:2013,month:3,day:26,title:'Dunfermline moves into interim administration',competition:'Club History',milestone:true},
{n:106,year:2013,month:4,day:11,title:'Dunfermline administration formally confirmed',competition:'Club History',milestone:true},
{n:105,year:2022,month:5,day:7,title:'Pars relegated to League One',competition:'Championship Play-off',note:'A late Queen’s Park goal at East End Park sealed relegation after a 1–0 play-off defeat.',milestone:true},
{n:104,year:2023,month:4,day:15,title:'Dunfermline are League One champions',competition:'League One',note:'A 5–0 win over Queen of the South secured the title for James McPake’s side.',milestone:true},
{n:103,year:1949,month:10,day:29,title:'Dunfermline reach their first League Cup final',competition:'Scottish League Cup Final',note:'The Pars lost 3–0 to East Fife at Hampden.',milestone:true},
{n:100,year:1972,month:4,day:27,title:'Rangers 3 Dunfermline 4',competition:'Scottish First Division',note:'Last Pars win at Ibrox Stadium'},
{n:99,year:2020,month:3,day:10,title:'Partick Thistle 1 Dunfermline 1',competition:'Ladbrokes Championship',note:'Last match before the Covid-19 lockdown'},
{n:98,year:1989,month:10,day:14,title:'Dunfermline 5 St Mirren 1',competition:'Scottish First Division'},
{n:97,year:2001,month:1,day:17,title:'Raja Casablanca 1 Dunfermline 3',competition:'Said Saddiki Testimonial'},
{n:96,year:1985,month:8,day:7,title:'Dunfermline 1 Aberdeen 0',competition:'Centenary Match'},
{n:95,year:1987,month:8,day:22,title:'Dunfermline 2 Celtic 1',competition:'Scottish Premier League',note:'First SPL win over Celtic'},
{n:94,year:2004,month:8,day:12,title:'FH Hafnarfjordur 2 Dunfermline 2',competition:'UEFA Cup First Round'},
{n:93,year:1965,month:12,day:25,title:'Rangers 2 Dunfermline 3',competition:'Scottish First Division',note:'Dunfermline’s first ever win at Ibrox'},
{n:92,year:1974,month:11,day:11,title:'Dunfermline 3 Celtic/Rangers Select 3',competition:'John Lunn Testimonial'},
{n:91,year:1966,month:3,day:5,title:'Dunfermline 2 Kilmarnock 1',competition:'Scottish Cup Quarter Final'},
{n:90,year:2000,month:8,day:7,title:'Dunfermline 0 Arsenal 3',competition:'Stadium Opener Friendly'},
{n:89,year:2003,month:9,day:20,title:'Dunfermline 0 Hibernian 0',competition:'Scottish Premier League',note:'First game on East End Park Astro'},
{n:88,year:2013,month:4,day:13,title:'Morton 0 Dunfermline 1',competition:'First Division'},
{n:87,year:1966,month:11,day:19,title:'Dunfermline 4 Celtic 5',competition:'Scottish First Division'},
{n:86,year:2007,month:8,day:8,title:'Dunfermline 0 Manchester United 4',competition:'Scott Thomson Testimonial'},
{n:85,year:1996,month:9,day:28,title:'Dunfermline 3 Raith Rovers 1',competition:'Scottish Premier League'},
{n:84,year:2003,month:7,day:27,title:'NEC Nijmegen 0 Dunfermline 1',competition:'Pre Season Friendly'},
{n:83,year:1988,month:5,day:7,title:'Celtic 1 Dunfermline 0',competition:'Scottish League Premier Division'},
{n:82,year:1994,month:10,day:1,title:'Dundee 4 Dunfermline 4',competition:'Scottish First Division'},
{n:81,year:2012,month:11,day:17,title:'Raith Rovers 1 Dunfermline 3',competition:'First Division'},
{n:80,year:1991,month:10,day:27,title:'Dunfermline 0 Hibernian 2',competition:'Skol Cup Final'},
{n:79,year:2005,month:12,day:26,title:'Dunfermline 3 Rangers 3',competition:'Scottish Premier League'},
{n:78,year:1961,month:2,day:25,title:'Aberdeen 3 Dunfermline 6',competition:'Scottish Cup Third Round'},
{n:77,year:2019,month:8,day:17,title:'Celtic 2 Dunfermline 1 aet',competition:'Betfred Cup Second Round'},
{n:76,year:2003,month:1,day:21,title:'Dunfermline 3 The Pars 1',competition:'Stewart Petrie Testimonial'},
{n:75,year:1968,month:9,day:18,title:'Dunfermline 10 Apoel FC 1',competition:'European Cup Winners Cup'},
{n:74,year:2016,month:9,day:24,title:'Dunfermline 4 St Mirren 3',competition:'SPFL Championship'},
{n:73,year:1960,month:3,day:19,title:'Dunfermline 3 Celtic 2',competition:'Scottish First Division',note:'Jock Stein’s first match in charge'},
{n:72,year:2002,month:3,day:23,title:'Dunfermline 2 Dundee 0',competition:'Scottish Premier League'},
{n:71,year:1988,month:2,day:22,title:'Dunfermline 2 Rangers 0',competition:'Scottish Cup Fourth Round'},
{n:70,year:1958,month:4,day:16,title:'Forfar Athletic 0 Dunfermline 1',competition:'Scottish Second Division'},
{n:69,year:2010,month:8,day:31,title:'Raith Rovers 3 Dunfermline 5',competition:'Reserve League Cup Final'},
{n:68,year:2007,month:5,day:26,title:'Dunfermline 0 Celtic 1',competition:'Scottish Cup Final'},
{n:67,year:2019,month:10,day:19,title:'Dunfermline 3 Ayr United 2',competition:'Ladbrokes Championship'},
{n:66,year:1966,month:9,day:17,title:'Dunfermline 5 Hibernian 6',competition:'Scottish First Division'},
{n:65,year:1998,month:11,day:15,title:'Dunfermline 2 Dundee United 1',competition:'Scottish Premier League'},
{n:64,year:2004,month:5,day:22,title:'Dunfermline 1 Celtic 3',competition:'Scottish Cup Final'},
{n:63,year:1995,month:5,day:21,title:'Aberdeen 3 Dunfermline 1',competition:'Premier Division Play-off'},
{n:62,year:1966,month:3,day:30,title:'Real Zaragoza 4 Dunfermline 2',competition:'Inter Cities Fairs Cup Quarter Final'},
{n:61,year:2018,month:9,day:8,title:'Boreham Wood 0 Dunfermline 0',competition:'Irn Bru Cup Second Round'},
{n:60,year:1968,month:5,day:18,title:'Dunfermline 1 Manchester City 1',competition:'North American Tour Friendly'},
{n:59,year:2000,month:4,day:22,title:'Inverness CT 1 Dunfermline 2',competition:'Scottish First Division'},
{n:58,year:1969,month:10,day:1,title:'Bordeaux 2 Dunfermline 0',competition:'Inter Cities Fairs Cup'},
{n:57,year:2005,month:5,day:15,title:'Dundee United 0 Dunfermline 1',competition:'Scottish Premier League'},
{n:56,year:2007,month:2,day:3,title:'Dunfermline 1 Hearts 0',competition:'Scottish Cup Fourth Round'},
{n:55,year:1989,month:5,day:13,title:'Dunfermline 1 Meadowbank Thistle 1',competition:'Scottish First Division'},
{n:54,year:1965,month:3,day:16,title:'Athletic Bilbao 2 Dunfermline 1',competition:'Inter Cities Fairs Cup'},
{n:53,year:2013,month:5,day:11,title:'Dunfermline 6 Forfar Athletic 1',competition:'Play Off Semi Final Second Leg'},
{n:52,year:1987,month:8,day:8,title:'Dunfermline 3 Hibernian 3',competition:'Scottish Premier Division'},
{n:51,year:2017,month:7,day:29,title:'Hearts 2 Dunfermline 2',competition:'Betfred Cup Group B'},
{n:50,year:2001,month:7,day:28,title:'Dunfermline 5 Motherwell 2',competition:'Premier League',note:'Debut for Jack de Gier'},
{n:49,year:2006,month:1,day:25,title:'Dunfermline 1 Livingston 0',competition:'League Cup Semi Final'},
{n:48,year:1961,month:9,day:12,title:'Dunfermline 4 St Patricks Athletic 1',competition:'European Cup Winners Cup',note:'Pars first match in European competition'},
{n:47,year:2018,month:12,day:29,title:'Falkirk 2 Dunfermline 4',competition:'Ladbrokes Championship'},
{n:46,year:1996,month:5,day:4,title:'Dunfermline 2 Airdrie 1',competition:'Scottish First Division'},
{n:45,year:1998,month:5,day:3,title:'Dunfermline 1 Celtic 1',competition:'Premier League',note:'Last day of terracing at East End Park'},
{n:44,year:2005,month:8,day:23,title:'Gretna 0 Dunfermline 1',competition:'League Cup Second Round'},
{n:43,year:2013,month:5,day:1,title:'Celtic 3 Dunfermline 1',competition:'SFA Youth Cup Final'},
{n:42,year:2011,month:4,day:30,title:'Morton 0 Dunfermline 2',competition:'Scottish First Division'},
{n:41,year:1986,month:4,day:29,title:'Stenhousemuir 0 Dunfermline 0',competition:'Scottish Second Division'},
{n:40,year:1996,month:4,day:27,title:'Dundee United 0 Dunfermline 1',competition:'Scottish First Division'},
{n:39,year:1968,month:4,day:27,title:'Dunfermline 3 Hearts 1',competition:'Scottish Cup Final'},
{n:38,year:1961,month:4,day:26,title:'Celtic 0 Dunfermline 2',competition:'Scottish Cup Final Replay'},
{n:37,year:1987,month:4,day:25,title:'Dunfermline 1 Queen of the South 0',competition:'Scottish First Division'},
{n:36,year:2007,month:4,day:24,title:'Dunfermline 1 Hibernian 0',competition:'Scottish Cup Semi Final Replay'},
{n:35,year:1970,month:1,day:14,title:'Dunfermline 3 Anderlecht 2',competition:'Inter Cities Fairs Cup Third Round'},
{n:34,year:2018,month:4,day:21,title:'Inverness CT 2 Dunfermline 2',competition:'Ladbrokes Championship'},
{n:33,year:2012,month:4,day:21,title:'St Mirren 4 Dunfermline 4',competition:'Scottish Premier League'},
{n:32,year:1968,month:1,day:27,title:'Celtic 0 Dunfermline 2',competition:'Scottish Cup First Round'},
{n:31,year:1991,month:9,day:24,title:'Dunfermline 1 Airdrieonians 1',competition:'League Cup Semi Final'},
{n:30,year:1959,month:4,day:18,title:'Dunfermline 10 Partick Thistle 1',competition:'Scottish First Division'},
{n:29,year:2004,month:8,day:26,title:'Dunfermline 1 FH Hafnarfjordur 2',competition:'UEFA Cup'},
{n:28,year:1962,month:12,day:19,title:'Dunfermline 6 Valencia 2',competition:'Inter Cities Fairs Cup'},
{n:27,year:2004,month:5,day:2,title:'Celtic 1 Dunfermline 2',competition:'Scottish Premier League'},
{n:26,year:1969,month:2,day:19,title:'West Bromwich Albion 0 Dunfermline 1',competition:'European Cup Winners Cup Quarter Final'},
{n:25,year:2002,month:6,day:28,title:'New Zealand 0 Dunfermline 1',competition:'Friendly'},
{n:24,year:1996,month:1,day:13,title:'Dunfermline 4 Clydebank 3',competition:'Scottish First Division'},
{n:23,year:2009,month:3,day:17,title:'Aberdeen 0 Dunfermline 0',competition:'Scottish Cup Quarter Final Replay'},
{n:22,year:2011,month:3,day:29,title:'Ross County 0 Dunfermline 1',competition:'First Division'},
{n:21,year:1969,month:4,day:9,title:'Dunfermline 1 Slovan Bratislava 1',competition:'European Cup Winners Cup Semi Final'},
{n:20,year:2005,month:9,day:20,title:'Kilmarnock 3 Dunfermline 4',competition:'League Cup Third Round'},
{n:19,year:2015,month:8,day:15,title:'Dunfermline 7 Cowdenbeath 1',competition:'Scottish League One'},
{n:18,year:2007,month:1,day:7,title:'Dunfermline 3 Rangers 2',competition:'Scottish Cup Third Round'},
{n:17,year:1961,month:4,day:5,title:'Dunfermline 1 St Mirren 0',competition:'Scottish Cup Semi Final Replay'},
{n:16,year:1986,month:1,day:4,title:'Threave Rovers 0 Dunfermline 5',competition:'Scottish Cup Second Round'},
{n:15,year:1968,month:4,day:3,title:'Dunfermline 2 St Johnstone 1',competition:'Scottish Cup Semi Final Replay'},
{n:14,year:2016,month:3,day:26,title:'Dunfermline 3 Brechin City 1',competition:'Scottish League One'},
{n:13,year:1962,month:10,day:31,title:'Dunfermline 2 Everton 0',competition:'Inter Cities Fairs Cup'},
{n:12,year:2013,month:4,day:27,title:'Partick Thistle 3 Dunfermline 3',competition:'First Division'},
{n:11,year:2001,month:2,day:17,title:'Dunfermline 2 Celtic 2',competition:'Scottish Cup Fourth Round'},
{n:10,year:2007,month:8,day:15,title:'Dunfermline 1 BK Hacken 1',competition:'UEFA Cup Qualifying'},
{n:9,year:2014,month:5,day:3,title:'Dunfermline 1 Rangers 1',competition:'Scottish League One'},
{n:8,year:1968,month:4,day:30,title:'Dunfermline 1 Celtic 2',competition:'Scottish First Division'},
{n:7,year:2005,month:5,day:7,title:'Dunfermline 5 Dundee 0',competition:'Scottish Premier League'},
{n:6,year:1962,month:2,day:13,title:'Ujpest Dozsa 4 Dunfermline 3',competition:'European Cup Winners Cup'},
{n:5,year:1986,month:4,day:19,title:'Dunfermline 4 East Stirling 0',competition:'Scottish Second Division'},
{n:4,year:1965,month:4,day:17,title:'Dunfermline 1 St Johnstone 1',competition:'Scottish First Division'},
{n:3,year:2004,month:4,day:20,title:'Dunfermline 3 Inverness Caley Thistle 2',competition:'Scottish Cup Semi Final Replay'},
{n:2,year:2011,month:4,day:24,title:'Dunfermline 2 Raith Rovers 1',competition:'First Division'},
{n:1,year:2013,month:8,day:24,title:'Stenhousemuir 4 Dunfermline 5',competition:'League One'}
];
