"use client";
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import './on-this-day.css';
import {curatedEvents as E,CuratedEvent} from './curated';
type Match={id:number;played_on:string|null;home_score:number|null;away_score:number|null;home_club_id:number|null;away_club_id:number|null;competition_season_id:number|null;round:string|null;attendance:number|null};
type Club={id:number;name:string}; type CS={id:number;display_name:string|null};
const U="https://uwhewuwnrcvrnclfzoge.supabase.co",K="sb_publishable_3qBGcpu8I6fytBGxdhJDNA_zOklTBeT",H={apikey:K,Authorization:`Bearer ${K}`};
const MONTHS=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
const md=(date:string)=>date.slice(5,10), mdOf=(m:number,d:number)=>`${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
export default function OnThisDay(){const now=new Date(),[month,setMonth]=useState(now.getMonth()+1),[day,setDay]=useState(now.getDate()),[matches,setMatches]=useState<Match[]>([]),[clubs,setClubs]=useState<Club[]>([]),[css,setCss]=useState<CS[]>([]);
useEffect(()=>{Promise.all([fetch(`${U}/rest/v1/matches?select=id,played_on,home_score,away_score,home_club_id,away_club_id,competition_season_id,round,attendance&played_on=not.is.null&order=played_on.desc`,{headers:H}).then(r=>r.json()),fetch(`${U}/rest/v1/clubs?select=id,name`,{headers:H}).then(r=>r.json()),fetch(`${U}/rest/v1/competition_seasons?select=id,display_name`,{headers:H}).then(r=>r.json())]).then(([m,c,s])=>{setMatches(Array.isArray(m)?m:[]);setClubs(Array.isArray(c)?c:[]);setCss(Array.isArray(s)?s:[])}).catch(()=>{})},[]);
const club=useMemo(()=>Object.fromEntries(clubs.map(c=>[c.id,c.name])),[clubs]),comp=useMemo(()=>Object.fromEntries(css.map(c=>[c.id,c.display_name||'Match'])),[css]);
const key=mdOf(month,day),curated=useMemo(()=>E.filter(x=>x.month===month&&x.day===day).sort((a,b)=>b.year-a.year),[month,day]),dayMatches=useMemo(()=>matches.filter(m=>m.played_on&&md(m.played_on)===key).sort((a,b)=>(b.played_on||'').localeCompare(a.played_on||'')),[matches,key]);
const curatedMatchKeys=useMemo(()=>new Set(curated.filter(e=>!e.milestone).map(e=>`${e.year}-${key}`)),[curated,key]),ordinary=dayMatches.filter(m=>m.played_on&&!curatedMatchKeys.has(m.played_on));
const total=curated.length+ordinary.length,covered=useMemo(()=>{const x=new Set(E.map(e=>mdOf(e.month,e.day)));matches.forEach(m=>m.played_on&&x.add(md(m.played_on)));return x.size},[matches]);
function surprise(){const keys=[...new Set([...E.map(e=>mdOf(e.month,e.day)),...matches.flatMap(m=>m.played_on?[md(m.played_on)]:[])])];if(!keys.length)return;const [mm,dd]=keys[Math.floor(Math.random()*keys.length)].split('-').map(Number);setMonth(mm);setDay(dd)}
function matchTitle(m:Match){const h=club[m.home_club_id||0]||'Home',a=club[m.away_club_id||0]||'Away',hs=m.home_score??'–',as=m.away_score??'–';return `${h} ${hs} ${a} ${as}`}
function card(e:CuratedEvent,i:number){return <article className={i===0?'lead':''} key={`c-${e.n}-${e.year}`}><div className="year">{e.year}</div><div className="story"><span>{e.milestone?'CLUB MILESTONE':`MEMORABLE MATCH #${e.n}`}</span><h2>{e.title}</h2><p>{e.competition}</p>{e.note&&<strong>{e.note}</strong>}</div></article>}
return <main className="otdPage"><section className="otdHero"><div><span>THE PARS · ON THIS DAY</span><h1>{String(day).padStart(2,'0')}<small>{MONTHS[month-1]}</small></h1><p>{total?`${total} ${total===1?'entry':'entries'} from this date in Dunfermline Athletic history.`:'This date is still awaiting a verified Pars event.'}</p></div><button onClick={surprise}>TAKE ME TO ANOTHER DAY ↗</button></section><section className="dateStrip"><select value={month} onChange={e=>setMonth(+e.target.value)}>{MONTHS.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</select><input type="number" min="1" max="31" value={day} onChange={e=>setDay(Math.max(1,Math.min(31,+e.target.value)))} /><span>{covered}/366 CALENDAR DATES CURRENTLY COVERED · {matches.length} DATED MATCHES</span></section><section className="otdStories">{curated.map(card)}{ordinary.map((m,i)=><article className={!curated.length&&i===0?'lead':''} key={`m-${m.id}`}><div className="year">{m.played_on?.slice(0,4)}</div><div className="story"><span>FROM THE MATCH ARCHIVE</span><h2>{matchTitle(m)}</h2><p>{comp[m.competition_season_id||0]||'Dunfermline Athletic match'}{m.round?` · ${m.round}`:''}</p>{m.attendance?<strong>Attendance: {m.attendance.toLocaleString()}</strong>:null}<Link href={`/match/?id=${m.id}`}>VIEW MATCH IN PARS DATABASE →</Link></div></article>)}{!total&&<div className="empty"><b>NOTHING HERE. YET.</b><h2>This is one of the remaining gaps.</h2><p>We are researching club milestones, tours, transfers and other archive material to give every calendar day a genuine Pars story.</p><button onClick={surprise}>SHOW ME A DAY WITH PARS HISTORY</button></div>}</section></main>}
