"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Player={id:number;slug:string;name:string;photo_url:string|null;appearances:number;goals:number};
const U="https://uwhewuwnrcvrnclfzoge.supabase.co",K="sb_publishable_3qBGcpu8I6fytBGxdhJDNA_zOklTBeT",H={apikey:K,Authorization:`Bearer ${K}`};
const ROUNDS=10;
function displayName(n:string){const p=n.split(',').map(x=>x.trim());return p.length===2?`${p[1]} ${p[0]}`:n.trim()}
function initials(n:string){return displayName(n).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function dayKey(){return new Date().toISOString().slice(0,10)}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function seeded(seed:number){let x=seed||1;return()=>{x=(Math.imul(x,1664525)+1013904223)>>>0;return x/4294967296}}
function makeSequence(pool:Player[],seed:number){const rand=seeded(seed);const shuffled=[...pool].sort(()=>rand()-.5);const out:Player[]=[];for(const p of shuffled){if(!out.length||p.appearances!==out[out.length-1].appearances)out.push(p);if(out.length===ROUNDS+1)break}return out}
export default function HigherLowerGame(){const [pool,setPool]=useState<Player[]>([]),[sequence,setSequence]=useState<Player[]>([]),[round,setRound]=useState(0),[score,setScore]=useState(0),[ended,setEnded]=useState(false),[revealed,setRevealed]=useState(false),[lastCorrect,setLastCorrect]=useState<boolean|null>(null),[practice,setPractice]=useState(false),[shared,setShared]=useState(false);useEffect(()=>{Promise.all([fetch(`${U}/rest/v1/players?select=id,slug,name,photo_url`,{headers:H}).then(r=>r.json()),fetch(`${U}/rest/v1/player_career_totals?select=player_id,appearances,goals`,{headers:H}).then(r=>r.json())]).then(([ps,ts])=>{const totals=new Map(ts.map((x:any)=>[x.player_id,x]));const good=(ps as any[]).map(p=>({...p,appearances:Number((totals.get(p.id) as any)?.appearances||0),goals:Number((totals.get(p.id) as any)?.goals||0)})).filter(p=>p.appearances>=20);setPool(good);const seq=makeSequence(good,hash(`higher-lower-${dayKey()}`));setSequence(seq);try{const s=JSON.parse(localStorage.getItem(`pars-higher-lower:${dayKey()}`)||'null');if(s?.ids?.join(',')===seq.map(x=>x.id).join(',')){setRound(s.round||0);setScore(s.score||0);setEnded(!!s.ended);setRevealed(!!s.revealed);setLastCorrect(s.lastCorrect??null)}}catch{}})},[]);useEffect(()=>{if(sequence.length&&!practice)localStorage.setItem(`pars-higher-lower:${dayKey()}`,JSON.stringify({ids:sequence.map(x=>x.id),round,score,ended,revealed,lastCorrect}))},[sequence,round,score,ended,revealed,lastCorrect,practice]);const left=sequence[round],right=sequence[round+1];const finished=ended||round>=ROUNDS;function choose(choice:'higher'|'lower'){if(!left||!right||revealed||finished)return;const correct=choice==='higher'?right.appearances>left.appearances:right.appearances<left.appearances;setRevealed(true);setLastCorrect(correct);if(correct)setScore(x=>x+1);else setEnded(true)}function next(){if(!lastCorrect)return;if(round+1>=ROUNDS){setRound(ROUNDS);setEnded(true);return}setRound(x=>x+1);setRevealed(false);setLastCorrect(null)}function startPractice(){if(!pool.length)return;setPractice(true);setSequence(makeSequence(pool,Math.floor(Math.random()*4294967295)));setRound(0);setScore(0);setEnded(false);setRevealed(false);setLastCorrect(null);setShared(false)}async function share(){const text=`PARS HIGHER OR LOWER ${practice?'Practice':dayKey()}\n${score} correct ${score===1?'answer':'answers'}${score===ROUNDS?' 🏆':''}\n\nPars Database`;try{if(navigator.share)await navigator.share({text});else await navigator.clipboard.writeText(text);setShared(true)}catch{}}
if(!left||!right)return <div className="hlShell"><div className="hlLoading">Selecting two Pars legends…</div></div>;
return <div className="hlShell"><header className="hlHeader"><span>DAILY STAT CHALLENGE</span><h1>HIGHER <em>OR</em> LOWER</h1><p>Does the next Dunfermline player have more or fewer career appearances for the Pars?</p></header><div className="hlMeta"><b>{practice?'PRACTICE':'TODAY\'S RUN'}</b><span>Score <strong>{score}</strong> · Round {Math.min(round+1,ROUNDS)}/{ROUNDS}</span></div>{!finished?<section className="hlArena"><article className="hlPlayer hlKnown"><div className="hlPortrait">{left.photo_url?<img src={left.photo_url} alt={displayName(left.name)}/>:<b>{initials(left.name)}</b>}</div><div className="hlPlayerInfo"><small>HAS</small><h2>{displayName(left.name)}</h2><strong>{left.appearances.toLocaleString()}</strong><span>Pars appearances</span></div></article><div className="hlVs">VS</div><article className={`hlPlayer hlMystery ${revealed?(lastCorrect?'isCorrect':'isWrong'):''}`}><div className="hlPortrait">{right.photo_url?<img src={right.photo_url} alt={displayName(right.name)}/>:<b>{initials(right.name)}</b>}</div><div className="hlPlayerInfo"><small>HAS</small><h2>{displayName(right.name)}</h2><strong>{revealed?right.appearances.toLocaleString():'?'}</strong><span>Pars appearances</span></div></article>{!revealed?<div className="hlChoices"><button onClick={()=>choose('higher')}>▲ HIGHER</button><span>than {displayName(left.name)}</span><button onClick={()=>choose('lower')}>▼ LOWER</button></div>:<div className={`hlVerdict ${lastCorrect?'good':'bad'}`}><b>{lastCorrect?'CORRECT':'FULL-TIME'}</b><span>{displayName(right.name)} made <strong>{right.appearances}</strong> Pars appearances.</span>{lastCorrect?<button onClick={next}>NEXT PLAYER →</button>:<button onClick={()=>setEnded(true)}>SEE RESULT →</button>}</div>}</section>:<section className="hlResult"><span>{score===ROUNDS?'PERFECT RUN':score>=7?'OUTSTANDING':score>=4?'SOLID PARS KNOWLEDGE':'BETTER LUCK NEXT TIME'}</span><strong>{score}</strong><h2>correct in a row</h2><p>{score===ROUNDS?'You survived all ten comparisons without putting a foot wrong.':`Your run ended after ${score} correct ${score===1?'comparison':'comparisons'}.`}</p><div><button onClick={share}>{shared?'COPIED ✓':'SHARE RESULT'}</button><button className="secondary" onClick={startPractice}>PLAY PRACTICE RUN</button></div></section>}<footer className="hlFooter"><button onClick={startPractice}>PRACTICE HIGHER OR LOWER →</button><Link href="/interactive/">← ALL INTERACTIVE GAMES</Link></footer></div>}
