"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Player={id:number;slug:string;name:string;position:string|null;photo_url:string|null;appearances:number;goals:number};
const U="https://uwhewuwnrcvrnclfzoge.supabase.co",K="sb_publishable_3qBGcpu8I6fytBGxdhJDNA_zOklTBeT",H={apikey:K,Authorization:`Bearer ${K}`};
const MAX=6;
function displayName(n:string){const p=n.split(',').map(x=>x.trim());return p.length===2?`${p[1]} ${p[0]}`:n.trim()}
function norm(n:string){return displayName(n).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function letters(n:string){return norm(n).replace(/[^A-Z]/g,'')}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function dayKey(){return new Date().toISOString().slice(0,10)}
function score(guess:string,answer:string){const g=letters(guess),a=letters(answer),out=Array(g.length).fill('absent'),left:Record<string,number>={};for(let i=0;i<a.length;i++){if(g[i]===a[i])out[i]='correct';else left[a[i]]=(left[a[i]]||0)+1}for(let i=0;i<g.length;i++){if(out[i]==='correct')continue;if((left[g[i]]||0)>0){out[i]='present';left[g[i]]--}}return out}
function initials(n:string){return displayName(n).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function pos(p:string|null){const s=(p||'').toLowerCase();if(s.includes('goal'))return'Goalkeeper';if(s.includes('def'))return'Defender';if(s.includes('mid'))return'Midfielder';if(s.includes('forw')||s.includes('strik'))return'Forward';return'Player'}
export default function PardleGame(){const [pool,setPool]=useState<Player[]>([]),[answer,setAnswer]=useState<Player|null>(null),[guesses,setGuesses]=useState<string[]>([]),[input,setInput]=useState(''),[practice,setPractice]=useState(false),[msg,setMsg]=useState(''),[shared,setShared]=useState(false);useEffect(()=>{Promise.all([fetch(`${U}/rest/v1/players?select=id,slug,name,position,photo_url`,{headers:H}).then(r=>r.json()),fetch(`${U}/rest/v1/player_career_totals?select=player_id,appearances,goals`,{headers:H}).then(r=>r.json())]).then(([ps,ts])=>{const t=new Map(ts.map((x:any)=>[x.player_id,x]));const good=(ps as any[]).map(p=>({...p,appearances:Number((t.get(p.id) as any)?.appearances||0),goals:Number((t.get(p.id) as any)?.goals||0)})).filter(p=>p.appearances>=10&&letters(p.name).length>=5);setPool(good);const key=dayKey(),a=good[hash(`pardle-${key}`)%good.length];setAnswer(a);try{const saved=JSON.parse(localStorage.getItem(`pardle:${key}`)||'null');if(saved?.answer===a.id)setGuesses(saved.guesses||[])}catch{}})},[]);useEffect(()=>{if(answer&&!practice)localStorage.setItem(`pardle:${dayKey()}`,JSON.stringify({answer:answer.id,guesses}))},[answer,guesses,practice]);const won=!!answer&&guesses.some(g=>letters(g)===letters(answer.name)),over=won||guesses.length>=MAX;const suggestions=useMemo(()=>input.length<2?[]:pool.filter(p=>displayName(p.name).toLowerCase().includes(input.toLowerCase())).slice(0,6),[input,pool]);function submit(e:FormEvent){e.preventDefault();if(!answer||over)return;const match=pool.find(p=>norm(p.name)===norm(input));if(!match){setMsg('Choose a player from the Pars archive.');return}setGuesses(x=>[...x,displayName(match.name)]);setInput('');setMsg('')}function newPractice(){if(!pool.length)return;setPractice(true);setGuesses([]);setInput('');setMsg('');setAnswer(pool[Math.floor(Math.random()*pool.length)])}async function share(){if(!answer)return;const rows=guesses.map(g=>score(g,answer.name).map(x=>x==='correct'?'🟥':x==='present'?'⬜':'⬛').join('')).join('\n');const text=`PARDLE ${practice?'Practice':dayKey()} ${won?`${guesses.length}/6`:'X/6'}\n\n${rows}\n\nPars Database`;try{if(navigator.share)await navigator.share({text});else await navigator.clipboard.writeText(text);setShared(true)}catch{}}
return <div className="pardleShell"><section className="pardleIntro"><div><span className="interactiveKicker">DAILY PARS CHALLENGE</span><h1>PAR<span>DLE</span></h1><p>Six attempts. One Dunfermline player. Name the Par from the club's history.</p></div><div className="pardleRules"><b>{practice?'PRACTICE':'TODAY\'S PARDLE'}</b><span>{practice?'Unlimited games':dayKey()}</span><small>Spaces and hyphens don't count. Red = right letter, right place. White = right letter, wrong place.</small></div></section><section className="pardleBoard">{!answer?<div className="pardleLoading">Selecting today's Par…</div>:<><div className="guessStack">{Array.from({length:MAX}).map((_,i)=>{const g=guesses[i];return <div className="guessRow" key={i}>{g?<><span className="guessName">{g}</span><span className="letterRun">{letters(g).split('').map((c,j)=><i className={score(g,answer.name)[j]} key={j}>{c}</i>)}</span></>:<span className="emptyGuess">ATTEMPT {i+1}</span>}</div>})}</div>{!over?<form className="pardleForm" onSubmit={submit}><label>Guess the player's full name</label><div className="pardleInput"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Start typing a Pars player…" autoComplete="off"/><button>GUESS</button></div>{suggestions.length>0&&<div className="pardleSuggestions">{suggestions.map(p=><button type="button" key={p.id} onClick={()=>setInput(displayName(p.name))}>{displayName(p.name)} <small>{p.appearances} apps</small></button>)}</div>}{msg&&<p className="pardleMessage">{msg}</p>}</form>:<div className="pardleReveal"><div className="revealPhoto">{answer.photo_url?<img src={answer.photo_url} alt={displayName(answer.name)}/>:<b>{initials(answer.name)}</b>}</div><div><span>{won?'YOU GOT THE PAR':'TODAY\'S PAR WAS'}</span><h2>{displayName(answer.name)}</h2><p>{pos(answer.position)} · <strong>{answer.appearances}</strong> appearances · <strong>{answer.goals}</strong> goals</p><div className="revealActions"><Link href={`/players/${answer.slug}/`}>View player profile →</Link><button onClick={share}>{shared?'COPIED ✓':'SHARE RESULT'}</button></div></div></div>}<div className="clueRail"><b>CLUES</b>{guesses.length>=1&&<span>Position <strong>{pos(answer.position)}</strong></span>}{guesses.length>=2&&<span>Appearances <strong>{answer.appearances}</strong></span>}{guesses.length>=3&&<span>Goals <strong>{answer.goals}</strong></span>}{guesses.length>=4&&answer.photo_url&&<span>Portrait <strong>Unlocked after guess 5</strong></span>}{guesses.length>=5&&answer.photo_url&&<span className="miniPortrait"><img src={answer.photo_url} alt="Player clue"/></span>}</div></>}</section><footer className="pardleFooter"><div><b>Want another go?</b><span>Practice mode picks another player from the archive and doesn't affect today's result.</span></div><button onClick={newPractice}>PRACTICE PARDLE →</button></footer></div>}
