"use client";
import {useEffect,useMemo,useState} from 'react';import ClubBadge from '../components/ClubBadge';import './polls.css';
const U='https://uwhewuwnrcvrnclfzoge.supabase.co',K='sb_publishable_3qBGcpu8I6fytBGxdhJDNA_zOklTBeT',H={apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'},POLL='favourite-match-25-years';
type O={id:string;title:string;played_on:string;competition:string;home_team:string;away_team:string;home_score:number;away_score:number;why_it_mattered:string;sort_order:number};type V={option_id:string};
export default function Polls(){const [opts,setOpts]=useState<O[]>([]),[votes,setVotes]=useState<V[]>([]),[chosen,setChosen]=useState(''),[voted,setVoted]=useState(false),[busy,setBusy]=useState(false),[err,setErr]=useState('');
async function load(){const [o,v]=await Promise.all([fetch(`${U}/rest/v1/poll_options?poll_id=eq.${POLL}&active=eq.true&order=sort_order`,{headers:H}).then(r=>r.json()),fetch(`${U}/rest/v1/poll_votes?poll_id=eq.${POLL}&select=option_id`,{headers:H}).then(r=>r.json())]);setOpts(o);setVotes(v)}
useEffect(()=>{load();setVoted(localStorage.getItem(`pars-poll-${POLL}`)==='1')},[]);const counts=useMemo(()=>{const x:Record<string,number>={};votes.forEach(v=>x[v.option_id]=(x[v.option_id]||0)+1);return x},[votes]);const total=votes.length;const leaders=[...opts].sort((a,b)=>(counts[b.id]||0)-(counts[a.id]||0)).slice(0,3);
async function vote(){if(!chosen||voted||busy)return;setBusy(true);setErr('');let token=localStorage.getItem('pars-voter-token');if(!token){token=crypto.randomUUID();localStorage.setItem('pars-voter-token',token)}const r=await fetch(`${U}/rest/v1/poll_votes`,{method:'POST',headers:{...H,Prefer:'return=minimal'},body:JSON.stringify({poll_id:POLL,option_id:chosen,voter_token:token})});if(r.ok){localStorage.setItem(`pars-poll-${POLL}`,'1');setVoted(true);await load()}else if(r.status===409){localStorage.setItem(`pars-poll-${POLL}`,'1');setVoted(true);await load()}else setErr('Your vote could not be recorded. Please try again.');setBusy(false)}
return <main className="pollPage"><section className="pollHero"><div><span>SUPPORTERS' CHOICE · POLL 01</span><h1>THE MATCH<br/><em>YOU'D RELIVE.</em></h1><p>Twenty-five Pars matches from the last 25 years. Cup runs, derby days, title-clinchers and glorious chaos. You get one vote.</p><div className="pollHeroMeta"><b>25</b><small>MEMORABLE MATCHES</small><b>{total}</b><small>VOTES CAST</small></div></div></section>{voted&&total>0&&<section className="podium"><div className="podiumHead"><span>LIVE STANDINGS</span><h2>THE PEOPLE HAVE SPOKEN.</h2></div><div className="podiumGrid">{leaders.map((m,i)=><article key={m.id}><b>#{i+1}</b><h3>{m.title}</h3><strong>{counts[m.id]||0}</strong><small>{Math.round((counts[m.id]||0)/total*100)}% OF VOTES</small></article>)}</div></section>}<section className="ballot"><header><span>THE BALLOT</span><h2>Pick one. No pressure.</h2><p>{voted?'Your vote is in. Live results are shown below.':'Select your favourite, then cast your vote at the bottom.'}</p></header><div className="matchGrid">{opts.map((m,i)=>{const n=counts[m.id]||0,p=total?Math.round(n/total*100):0;return <button disabled={voted} onClick={()=>setChosen(m.id)} className={`matchCard ${chosen===m.id?'selected':''}`} key={m.id}><div className="cardNo">{String(i+1).padStart(2,'0')}</div><div className="date">{new Date(m.played_on+'T12:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()} · {m.competition}</div><div className="fixture"><div><ClubBadge name={m.home_team} size="sm"/><span>{m.home_team}</span></div><strong>{m.home_score}<i>–</i>{m.away_score}</strong><div><ClubBadge name={m.away_team} size="sm"/><span>{m.away_team}</span></div></div><p>{m.why_it_mattered}</p>{voted&&<div className="result"><div style={{width:`${p}%`}}/><span>{p}% · {n} vote{n===1?'':'s'}</span></div>} {!voted&&<span className="pick">{chosen===m.id?'SELECTED ✓':'SELECT THIS MATCH'}</span>}</button>})}</div>{!voted&&<div className="voteDock"><div><small>YOUR PICK</small><strong>{opts.find(x=>x.id===chosen)?.title||'Choose a match above'}</strong></div><button disabled={!chosen||busy} onClick={vote}>{busy?'CASTING…':'CAST MY VOTE →'}</button></div>}{err&&<p className="pollError">{err}</p>}</section><section className="pollSource"><p>The shortlist takes inspiration from the Dunfermline Athletic Heritage Trust's <b>100 Memorable Matches</b> archive, with fixtures cross-referenced against the Pars Database.</p><a href="https://daht.org.uk/news.php?c=Club+History&sc=100%20Memorable%20Matches" target="_blank" rel="noreferrer">EXPLORE THE HERITAGE TRUST SERIES ↗</a></section></main>}
